on: [push, pull_request]
name: Generate Coveralls report
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 5.32.1
      - name: Run with coverage checking
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm --installdeps .
          cpanm Devel::Cover::Report::Coveralls
          sudo --preserve-env=GITHUB_TOKEN /opt/hostedtoolcache/perl/5.32.1/x64/bin/cover -test -report Coveralls
